backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/img"
public_folder: "/assets/img"
collections:
  - name: "courses"
    label: "Courses"
    label_singular: 'Course'
    folder: "src/Courses"
    path: '{{course}}/{{slug}}'
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "model.njk" }
      - { label: "Course", name: "course", widget: "hidden", default: "Microeconomics" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "models" }
      - { label: "Body", name: "body", widget: "text" }
    meta: { path: { label: Parent, widget: parent, index_file: 'index' } }